// SteamAbi.h - hand-declared binary layout for the subset of the Steamworks API
// that Al Bhed Workshop calls inside the FFX HD process.
//
// WHY THIS FILE EXISTS
// The game ships steam_api.dll at
//   G:\Steam\steamapps\common\FINAL FANTASY FFX&FFX-2 HD Remaster\steam_api.dll
// (32-bit, 86 exports, file version 02.37.91.26). That DLL exports no flat API, so
// there is no SteamAPI_ISteamNetworking_SendP2PPacket to call. Every interface call
// has to go through a C++ vtable. There is no Steamworks SDK on this machine and the
// mod does not link one. So we declare the layout ourselves, here, once.
//
// Getting a slot index wrong here means calling an arbitrary function with the wrong
// arguments inside the game process. Do not edit this file from memory. Every fact
// below carries a provenance comment naming the source it came from. If you need to
// add something, go verify it the same way and write down where you got it.
//
// HOW THE FACTS BELOW WERE ESTABLISHED
//
//  [S1] Valve's own SDK headers, version-pinned, from Valve's Proton repository:
//       https://raw.githubusercontent.com/ValveSoftware/Proton/proton_8.0/
//         lsteamclient/steamworks_sdk_131/isteamnetworking.h
//       (also isteamclient.h, steamclientpublic.h, steam_api.h, steamtypes.h from the
//       same steamworks_sdk_131 directory). This is Valve shipping Valve's own SDK, so
//       it is a primary source, not a mirror.
//
//       We pinned 1.31 because that is the SDK whose STEAMCLIENT_INTERFACE_VERSION is
//       "SteamClient016", which is the string present in the game's steam_api.dll. We
//       swept steamworks_sdk_125 through _142 and confirmed:
//         SDK 1.25 - 1.28 -> SteamClient012
//         SDK 1.29        -> SteamClient014
//         SDK 1.30        -> SteamClient015
//         SDK 1.31        -> SteamClient016   <-- matches the shipped DLL
//         SDK 1.32 - 1.42 -> SteamClient017
//       So the DLL is SDK 1.31, slightly older than the 1.34-1.37 we first guessed.
//       It does not matter for networking: isteamnetworking.h is byte-for-byte
//       IDENTICAL (md5 300006747a99ccf176155b1333f6a87f) across every one of
//       steamworks_sdk_125 through _142, and every one of them says
//       STEAMNETWORKING_INTERFACE_VERSION "SteamNetworking005". The interface simply
//       did not change over that whole span, so the layout below is not sensitive to
//       which of those SDKs the DLL was actually built from.
//
//  [S2] SteamRE/open-steamworks, which is reverse engineered from the real shipping
//       steamclient.dll rather than copied from a header:
//       https://raw.githubusercontent.com/SteamRE/open-steamworks/master/
//         Open%20Steamworks/ISteamNetworking005.h   (and ISteamClient016.h)
//       Independent of [S1] and it agrees on method order and signatures.
//
//  [S3] The actual MSVC x86 compiler on this machine, 19.29.30159 for x86, asked to
//       dump the layout it really produces with -d1reportSingleClassLayout and to emit
//       the real call sequence with -FAs. This is the compiler that builds this mod, so
//       it is the final authority on vtable order, struct offsets and argument passing.
//       Transcripts of those runs are quoted inline below.
//
//  Cross-check that caught nothing but is worth recording: an independent mirror of a
//  NEWER SDK (SteamNetworking006, julianxhokaxhiu/SteamworksSDKCI) lists the same 22
//  methods in the same order. 006 differs from 005 only by swapping uint32 nIP for
//  SteamIPAddress_t in the four legacy socket methods. The P2P half, slots 0 to 7, is
//  unchanged between 005 and 006.
//
// CALLING CONVENTION, IN ONE PARAGRAPH
// These are MSVC C++ virtual methods on 32-bit Windows, so they are __thiscall: the
// interface pointer goes in ECX, the declared arguments are pushed on the stack right
// to left, and the CALLEE pops them. Verified from real codegen in [S3], see the
// disassembly quoted above ISteamNetworking005 below. The easy and safe way to call
// them is to declare the abstract class in this file and let MSVC do it, which is what
// ISteamNetworking005 below is for. Raw __thiscall function pointer typedefs are also
// provided for the cases where you want to bypass the class, and they were verified to
// produce byte-identical code to the virtual call.
//
// Style note: this header is deliberately plain C++ with no SDK and no STL. The only
// include is <stddef.h>, for offsetof, so the static_asserts at the bottom can check
// that whatever compiler you are using actually agrees with the offsets written here.

#ifndef WORKSHOP_STEAMABI_H
#define WORKSHOP_STEAMABI_H

#include <stddef.h>

#if !defined(_WIN32)
#error "SteamAbi.h describes the 32-bit Windows MSVC ABI only."
#endif
#if defined(_WIN64)
#error "SteamAbi.h is 32-bit only. The game and this mod are x86."
#endif

namespace workshop
{

	// ---------------------------------------------------------------------------
	// Fixed width types.
	//
	// Provenance: names and widths match steamtypes.h from [S1] steamworks_sdk_131.
	// We declare our own rather than include the SDK so this header stands alone.
	// They live in namespace workshop so they cannot collide with anything.
	// ---------------------------------------------------------------------------

	typedef unsigned char uint8;
	typedef signed char int8;
	typedef unsigned short uint16;
	typedef short int16;
	typedef unsigned int uint32;
	typedef int int32;
	typedef unsigned long long uint64;
	typedef long long int64;

	typedef int HSteamPipe;
	typedef int HSteamUser;
	typedef uint64 SteamAPICall_t;

	// Legacy socket handles. Present so the vtable below is complete. We do not call
	// the socket API. Provenance: [S1] isteamnetworking.h lines 83-84.
	typedef uint32 SNetSocket_t;
	typedef uint32 SNetListenSocket_t;

	// ---------------------------------------------------------------------------
	// CSteamID
	//
	// Provenance: [S1] steamworks_sdk_131/steamclientpublic.h, class CSteamID at line
	// 402, sitting inside a "#pragma pack( push, 1 )" that opens at line 397. The real
	// SDK class is a union of a bitfield struct and a uint64:
	//
	//     union SteamID_t {
	//         struct SteamIDComponent_t {
	//             uint32       m_unAccountID       : 32;   // bits  0..31
	//             unsigned int m_unAccountInstance : 20;   // bits 32..51
	//             unsigned int m_EAccountType      :  4;   // bits 52..55
	//             EUniverse    m_EUniverse         :  8;   // bits 56..63
	//         } m_comp;
	//         uint64 m_unAll64Bits;
	//     } m_steamid;
	//
	// It declares no virtual functions, so there is no vptr and the object is exactly
	// its 8 payload bytes. [S3] confirms with the real compiler:
	//
	//     class CSteamID  size(8):
	//      0   | SteamID_t m_steamid
	//
	// HOW IT IS PASSED BY VALUE, which is the detail that silently misaligns argument
	// lists if you get it wrong. On MSVC x86 a class passed by value is copied onto the
	// stack, it is never passed in a register and it is never silently turned into a
	// hidden pointer, regardless of whether it has constructors. So a by-value CSteamID
	// occupies exactly 8 bytes of the argument area, low dword at the lower address,
	// which is identical to passing a uint64 by value. [S3] proves it. Compiling
	//
	//     p->SendP2PPacket( CSteamID( rawSteamId ), data, len, k_EP2PSendReliable, 0 );
	//
	// gave this, with rawSteamId declared as a plain uint64:
	//
	//     mov  ecx, DWORD PTR _p$[esp-4]        ; this -> ECX
	//     push 0                                ; nChannel        (pushed first = last arg)
	//     push 2                                ; eP2PSendType
	//     push DWORD PTR _len$[esp+4]           ; cubData
	//     mov  eax, DWORD PTR [ecx]             ; load vtable
	//     push DWORD PTR _data$[esp+8]          ; pubData
	//     push DWORD PTR _rawSteamId$[esp+16]   ; CSteamID high dword
	//     mov  eax, DWORD PTR [eax]             ; vtable[0] = SendP2PPacket
	//     push DWORD PTR _rawSteamId$[esp+16]   ; CSteamID low dword (esp moved by 4)
	//     call eax
	//     ret  0                                ; caller does NOT clean up -> callee pops
	//
	// Two pushes of the same uint64, high dword then low dword, and no stack fixup after
	// the call. That is a little-endian 8-byte value in the argument area and a
	// callee-pops convention, exactly as a uint64 argument to a __thiscall method.
	//
	// CONSEQUENCE, and this is the practical rule for this codebase: everywhere a Steam
	// method takes a CSteamID by value, we declare the parameter as uint64 instead. It is
	// byte-for-byte the same and it removes a whole category of mistake. Where a method
	// takes CSteamID*, we use SteamId* so the 8 bytes are still named.
	// ---------------------------------------------------------------------------

#pragma pack(push, 1)

	// Plain 8-byte stand-in for CSteamID. POD, no constructors, no vtable, alignment 1,
	// so it can sit inside the callback structs at the same offsets the SDK gives them.
	struct SteamId
	{
		uint64 m_unAll64Bits;
	};

#pragma pack(pop)

	// Build one from a raw uint64. A SteamID you got from the Steam API, from a lobby
	// member list, or out of a config file is already in this form, so this is just a
	// cast with a name on it.
	inline SteamId MakeSteamId(uint64 raw)
	{
		SteamId id;
		id.m_unAll64Bits = raw;
		return id;
	}

	inline uint64 SteamIdToUint64(const SteamId& id)
	{
		return id.m_unAll64Bits;
	}

	// Field accessors, in case you ever need to sanity check that a SteamID really is an
	// individual account on the public universe before trusting it.
	// Bit positions from the bitfield widths in [S1] steamclientpublic.h quoted above.
	inline uint32 SteamIdAccountId(uint64 raw)
	{
		return (uint32)(raw & 0xFFFFFFFFull);
	}
	inline uint32 SteamIdAccountInstance(uint64 raw)
	{
		return (uint32)((raw >> 32) & 0xFFFFFull);
	}
	inline uint32 SteamIdAccountType(uint64 raw)
	{
		return (uint32)((raw >> 52) & 0xFull);
	}
	inline uint32 SteamIdUniverse(uint64 raw)
	{
		return (uint32)((raw >> 56) & 0xFFull);
	}

	// Provenance: [S1] steamclientpublic.h, EUniverse and EAccountType. Only the two
	// values we would ever check against are named here.
	enum
	{
		k_EUniversePublic_value = 1
	};
	enum
	{
		k_EAccountTypeIndividual_value = 1
	};

	// ---------------------------------------------------------------------------
	// EP2PSend
	//
	// Provenance: [S1] steamworks_sdk_131/isteamnetworking.h lines 33-56, verbatim
	// enumerator values. Corroborated by [S2] and by the SteamNetworking006 mirror.
	//
	// MAXIMUM PAYLOAD PER MODE. This is what the Valve header itself states, in its own
	// comments on each enumerator, and it is the answer to "can I go above 1200 bytes":
	//
	//   k_EP2PSendUnreliable            max 1200 bytes. The header says "Basic UDP send.
	//                                   Packets can't be bigger than 1200 bytes (your
	//                                   typical MTU size)." Can be lost, can arrive out
	//                                   of order. If NAT traversal is still in progress
	//                                   the packet is batched rather than dropped.
	//
	//   k_EP2PSendUnreliableNoDelay     max 1200 bytes, same as above, except that if the
	//                                   P2P connection is not established yet the packet
	//                                   is thrown away instead of batched. The header
	//                                   warns that using this for the first packet to a
	//                                   host "almost guarantees the packet will be
	//                                   dropped". Meant for voice. Do not use it for
	//                                   anything we care about.
	//
	//   k_EP2PSendReliable              up to 1 MB in a single message. YES, it fragments
	//                                   for you: the header says it "Does fragmentation/
	//                                   re-assembly of messages under the hood, as well as
	//                                   a sliding window for efficient sends of large
	//                                   chunks of data." So a reliable send above 1200
	//                                   bytes is legal and handled, it is not an error and
	//                                   you do not have to split it yourself.
	//
	//   k_EP2PSendReliableWithBuffering up to 1 MB as well, plus Nagle: sends accumulate
	//                                   until roughly one MTU (~1200 bytes) or about 200 ms
	//                                   have passed. Because the reliable stream is ordered
	//                                   you can queue several small buffered sends and then
	//                                   issue one plain k_EP2PSendReliable to flush them.
	//
	// So for Al Bhed Workshop: the 1200 byte cap you are holding yourself to is REQUIRED
	// for the two unreliable modes and is NOT required for the two reliable ones. Keep
	// capping the frequent unreliable traffic at 1200. Reliable control messages may
	// exceed it safely up to 1 MB, which is far more headroom than 3 players need.
	// ---------------------------------------------------------------------------

	enum EP2PSend
	{
		k_EP2PSendUnreliable = 0,
		k_EP2PSendUnreliableNoDelay = 1,
		k_EP2PSendReliable = 2, // the reliable one
		k_EP2PSendReliableWithBuffering = 3
	};

	// Payload ceilings, from the header comments quoted above. Named so call sites can
	// assert against them instead of hardcoding a number.
	enum
	{
		k_cbMaxP2PPacketUnreliable = 1200
	};
	enum
	{
		k_cbMaxP2PPacketReliable = 1024 * 1024
	};

	// ---------------------------------------------------------------------------
	// EP2PSessionError
	//
	// Provenance: [S1] isteamnetworking.h lines 19-29. This is the value that lands in
	// P2PSessionConnectFail_t::m_eP2PSessionError and in
	// P2PSessionState_t::m_eP2PSessionError.
	//
	// Note on 1.31 versus later SDKs: 1.31 names all five. Newer SDKs mark 1 and 3 as
	// _DELETED but keep the numeric values, so the numbers are stable either way.
	// The header's own note on k_EP2PSessionErrorTimeout is worth keeping: it usually
	// means the peer never called AcceptP2PSessionWithUser, and corporate firewalls can
	// also cause it, in which case UDP ports 3478, 4379 and 4380 need to be open outbound.
	// ---------------------------------------------------------------------------

	enum EP2PSessionError
	{
		k_EP2PSessionErrorNone = 0,
		k_EP2PSessionErrorNotRunningApp = 1,          // peer is not running the same game
		k_EP2PSessionErrorNoRightsToApp = 2,          // local user does not own the app
		k_EP2PSessionErrorDestinationNotLoggedIn = 3, // peer is not connected to Steam
		k_EP2PSessionErrorTimeout = 4,                // peer never answered, see note above
		k_EP2PSessionErrorMax = 5
	};

	// ---------------------------------------------------------------------------
	// P2PSessionState_t, the struct GetP2PSessionState fills in.
	//
	// Provenance: [S1] isteamnetworking.h lines 68-78 for field order and types. The
	// struct sits inside a packing block that is pack(4) when VALVE_CALLBACK_PACK_SMALL
	// and pack(8) when VALVE_CALLBACK_PACK_LARGE. Which one applies is decided in
	// [S1] isteamclient.h lines 24-33:
	//
	//     #if defined(__linux__) || defined(__APPLE__)
	//     #define VALVE_CALLBACK_PACK_SMALL
	//     #else
	//     #define VALVE_CALLBACK_PACK_LARGE
	//     #endif
	//
	// We are Windows, so it is VALVE_CALLBACK_PACK_LARGE, that is #pragma pack(8).
	// Since no member here needs more than 4-byte alignment, pack(8) changes nothing and
	// the layout is the natural one.
	//
	// [S3] confirms with the real compiler, offsets and total size:
	//
	//     class P2PSessionState_t  size(20):
	//      0   | m_bConnectionActive
	//      1   | m_bConnecting
	//      2   | m_eP2PSessionError
	//      3   | m_bUsingRelay
	//      4   | m_nBytesQueuedForSend
	//      8   | m_nPacketsQueuedForSend
	//     12   | m_nRemoteIP
	//     16   | m_nRemotePort
	//          | <alignment member> (size=2)
	//
	// Total size 20 bytes, with 2 bytes of tail padding after m_nRemotePort. Zero it
	// before the call if you plan to read fields after a false return.
	// ---------------------------------------------------------------------------

#pragma pack(push, 8)

	struct P2PSessionState_t
	{
		uint8 m_bConnectionActive;     // +0  nonzero once the connection is open
		uint8 m_bConnecting;           // +1  nonzero while still trying
		uint8 m_eP2PSessionError;      // +2  EP2PSessionError, last error seen
		uint8 m_bUsingRelay;           // +3  nonzero if routed via a Steam relay (TURN)
		int32 m_nBytesQueuedForSend;   // +4
		int32 m_nPacketsQueuedForSend; // +8
		uint32 m_nRemoteIP;            // +12 may be a relay address, not the peer
		uint16 m_nRemotePort;          // +16
		                               // +18 two bytes tail padding, size is 20
	};

#pragma pack(pop)

	// ---------------------------------------------------------------------------
	// Callback ids and callback structs.
	//
	// Provenance for the base: [S1] steamworks_sdk_131/isteamclient.h declares the bases
	// as a run of single-enumerator enums. The networking one is
	//
	//     enum { k_iSteamNetworkingCallbacks = 1200 };
	//
	// so the Networking callback base is 1200. For context, neighbours are
	// k_iSteamUserCallbacks = 100, k_iSteamFriendsCallbacks = 300,
	// k_iSteamMatchmakingCallbacks = 500, k_iSteamUtilsCallbacks = 700,
	// k_iSteamUserStatsCallbacks = 1100, k_iClientRemoteStorageCallbacks = 1300.
	//
	// Provenance for the structs and their offsets: [S1] isteamnetworking.h lines 275-302,
	// inside the same pack(8) block as P2PSessionState_t. Confirmed by [S3]:
	//
	//     class P2PSessionRequest_t      size(8):
	//      0   | CSteamID m_steamIDRemote
	//
	//     class P2PSessionConnectFail_t  size(9):
	//      0   | CSteamID m_steamIDRemote
	//      8   | m_eP2PSessionError
	//
	// P2PSessionConnectFail_t really is 9 bytes, not 12. That is not a mistake. CSteamID
	// was declared under pack(1) at its own definition, so its alignment requirement is 1,
	// and an enclosing pack(8) can only ever lower alignment, never raise it. So the
	// uint8 lands at +8 and there is no tail padding. If you declare these structs with a
	// plain uint64 in place of CSteamID instead of a pack(1) type, the uint64's 8-byte
	// alignment makes the struct 16 bytes and GetCallbackSizeBytes starts lying to Steam.
	// That is why SteamId above is pack(1). The static_asserts at the bottom of this file
	// will fail loudly if that ever drifts.
	// ---------------------------------------------------------------------------

	enum
	{
		k_iSteamNetworkingCallbacks = 1200
	};

#pragma pack(push, 8)

	// Posted when a peer sends us a packet and we have no session with them yet. Respond
	// with AcceptP2PSessionWithUser if you want to talk to them. If you ignore it and the
	// peer keeps sending, it is posted again periodically.
	// Provenance: [S1] isteamnetworking.h lines 275-279.
	struct P2PSessionRequest_t
	{
		enum
		{
			k_iCallback = k_iSteamNetworkingCallbacks + 2
		};                       // = 1202
		SteamId m_steamIDRemote; // +0, the user who wants to talk to us
	};

	// Posted when packets cannot get through to a peer. Everything still queued for that
	// peer is dropped. Further sends retry the connection.
	// Provenance: [S1] isteamnetworking.h lines 285-290.
	struct P2PSessionConnectFail_t
	{
		enum
		{
			k_iCallback = k_iSteamNetworkingCallbacks + 3
		};                        // = 1203
		SteamId m_steamIDRemote;  // +0, who we were sending to
		uint8 m_eP2PSessionError; // +8, EP2PSessionError
	};

	// Only here so the numbering is complete and nobody later assumes +1 is free. This
	// belongs to the legacy socket API, which we do not use.
	// Provenance: [S1] isteamnetworking.h lines 295-302.
	struct SocketStatusCallback_t
	{
		enum
		{
			k_iCallback = k_iSteamNetworkingCallbacks + 1
		}; // = 1201
		SNetSocket_t m_hSocket;
		SNetListenSocket_t m_hListenSocket;
		SteamId m_steamIDRemote;
		int m_eSNetSocketState;
	};

#pragma pack(pop)

	// Spelled out as plain integers so they can be read at a glance and compared against
	// anything you see in a debugger.
	enum
	{
		k_iCallback_P2PSessionRequest = 1202
	};
	enum
	{
		k_iCallback_P2PSessionConnectFail = 1203
	};

	// ---------------------------------------------------------------------------
	// ISteamNetworking005 - THE MAIN DELIVERABLE
	//
	// Provenance: declaration order is taken verbatim from [S1]
	// steamworks_sdk_131/isteamnetworking.h, class ISteamNetworking at line 126 through
	// line 261, followed at line 262 by
	//     #define STEAMNETWORKING_INTERFACE_VERSION "SteamNetworking005"
	// so this class IS SteamNetworking005.
	//
	// WHY DECLARATION ORDER IS THE VTABLE ORDER. For MSVC with single inheritance, no
	// virtual bases, and no overloaded virtual names, the vtable is emitted in declaration
	// order. ISteamNetworking satisfies all three: it has no base class, and all 22 method
	// names are distinct, so there is no overload group for MSVC to reorder. (MSVC DOES
	// reorder overload groups, and that bites us in CCallbackBase further down, so the "no
	// overloads" part is a real precondition and not boilerplate.)
	//
	// Rather than trust that reasoning, [S3] was asked to dump what it actually emits.
	// Compiling this exact class with -d1reportSingleClassLayoutISteamNetworking gave:
	//
	//     class ISteamNetworking  size(4):
	//      0   | {vfptr}
	//
	//     ISteamNetworking::$vftable@:
	//      0   | &ISteamNetworking::SendP2PPacket
	//      1   | &ISteamNetworking::IsP2PPacketAvailable
	//      2   | &ISteamNetworking::ReadP2PPacket
	//      3   | &ISteamNetworking::AcceptP2PSessionWithUser
	//      4   | &ISteamNetworking::CloseP2PSessionWithUser
	//      5   | &ISteamNetworking::CloseP2PChannelWithUser
	//      6   | &ISteamNetworking::GetP2PSessionState
	//      7   | &ISteamNetworking::AllowP2PPacketRelay
	//      8   | &ISteamNetworking::CreateListenSocket
	//      9   | &ISteamNetworking::CreateP2PConnectionSocket
	//     10   | &ISteamNetworking::CreateConnectionSocket
	//     11   | &ISteamNetworking::DestroySocket
	//     12   | &ISteamNetworking::DestroyListenSocket
	//     13   | &ISteamNetworking::SendDataOnSocket
	//     14   | &ISteamNetworking::IsDataAvailableOnSocket
	//     15   | &ISteamNetworking::RetrieveDataFromSocket
	//     16   | &ISteamNetworking::IsDataAvailable
	//     17   | &ISteamNetworking::RetrieveData
	//     18   | &ISteamNetworking::GetSocketInfo
	//     19   | &ISteamNetworking::GetListenSocketInfo
	//     20   | &ISteamNetworking::GetSocketConnectionType
	//     21   | &ISteamNetworking::GetMaxPacketSize
	//
	//     ... this adjustor: 0   (for every method, so no thunks)
	//
	// and [S2], reverse engineered from the shipping steamclient.dll rather than from a
	// header, lists the same 22 methods in the same order with the same signatures. Three
	// sources agree. The object itself is 4 bytes: just the vtable pointer, no data.
	//
	// THE DEFAULT ARGUMENT TRAP. In the SDK header, slots 0, 1 and 2 declare
	// "int nChannel = 0". A default argument is a source-level convenience that the CALLER
	// fills in. It does not exist in the binary and the callee always expects the argument
	// to be there. We therefore declare nChannel with NO default below, so the compiler
	// forces every call site to pass it. [S2], working from the binary, also shows these
	// parameters as mandatory, which is the same observation from the other direction.
	// Pass 0 unless you actually want a separate channel.
	//
	// CSteamID parameters are declared as uint64 here. See the CSteamID block above for the
	// proof that this is byte-identical, and for why we prefer it.
	//
	// RETURN VALUES. Every method here returns bool, uint32 or int, so they all come back
	// in EAX and there is no struct return anywhere in this interface. No hidden return
	// pointer argument, nothing to get wrong. One caveat: MSVC returns bool in AL and the
	// upper 24 bits of EAX are not guaranteed, so compare against zero on the byte. The
	// declarations below use bool, which makes the compiler do that for you. If you ever
	// hand-roll a thunk, declare the return as bool, not int.
	//
	// HOW TO USE IT. Get the pointer from the steam_api.dll export "SteamNetworking"
	// (see the export block near the bottom of this file) and reinterpret_cast it to
	// ISteamNetworking005*. Then call methods normally and MSVC emits the correct
	// __thiscall sequence. Do not instantiate this class and never inherit from it to
	// "implement" it - it exists only as a shape to cast onto Valve's object.
	// ---------------------------------------------------------------------------

	class ISteamNetworking005
	{
	public:
		// --- Session-less P2P API. This is the part we actually use. ---

		// Slot 0. Sends a packet to a peer, opening the session on demand. The first
		// packet to a peer may be delayed while NAT traversal runs. If it cannot get
		// through you get a P2PSessionConnectFail_t. See EP2PSend above for the per-mode
		// payload ceilings: 1200 bytes unreliable, 1 MB reliable with automatic
		// fragmentation. eP2PSendType is an EP2PSend. nChannel has no default here on
		// purpose, pass 0.
		virtual bool SendP2PPacket(uint64 steamIDRemote, const void* pubData, uint32 cubData,
		    EP2PSend eP2PSendType, int nChannel) = 0;

		// Slot 1. True if a packet is waiting on nChannel, and writes its size to
		// *pcubMsgSize so you can size the read buffer.
		virtual bool IsP2PPacketAvailable(uint32* pcubMsgSize, int nChannel) = 0;

		// Slot 2. Reads one packet. Writes the byte count to *pcubMsgSize and the sender to
		// *psteamIDRemote. Non-blocking, returns false when nothing is queued. If cubDest
		// is smaller than the message the message is TRUNCATED, so call
		// IsP2PPacketAvailable first or keep a buffer at least k_cbMaxP2PPacketUnreliable
		// for unreliable traffic.
		virtual bool ReadP2PPacket(void* pubDest, uint32 cubDest, uint32* pcubMsgSize,
		    SteamId* psteamIDRemote, int nChannel) = 0;

		// Slot 3. Accept an incoming session. Normally called in response to
		// P2PSessionRequest_t, but it is safe to call it more than once for the same user,
		// and calling SendP2PPacket to a peer implicitly accepts their pending request.
		// That second fact is what makes the no-callback approach work, see the
		// CCallbackBase block below.
		virtual bool AcceptP2PSessionWithUser(uint64 steamIDRemote) = 0;

		// Slot 4. Done talking to a peer, release the resources. If they send again you get
		// a fresh P2PSessionRequest_t.
		virtual bool CloseP2PSessionWithUser(uint64 steamIDRemote) = 0;

		// Slot 5. Done with one channel to a peer. When every channel to that peer is
		// closed the session itself closes.
		virtual bool CloseP2PChannelWithUser(uint64 steamIDRemote, int nChannel) = 0;

		// Slot 6. Fills in P2PSessionState_t. Returns false if there is no session. The SDK
		// header calls this debug-only, so treat the contents as diagnostics, not as
		// control flow.
		virtual bool GetP2PSessionState(uint64 steamIDRemote, P2PSessionState_t* pConnectionState) = 0;

		// Slot 7. Allow or forbid falling back to Steam's relay servers when a direct
		// connection cannot be made. Relay is ALLOWED BY DEFAULT, so you do not need to
		// call this to get relaying. It only affects connections created after the call,
		// plus existing ones that later reconnect.
		virtual bool AllowP2PPacketRelay(bool bAllow) = 0;

		// --- Legacy Berkeley-sockets style API, slots 8 to 21. ---
		//
		// Listed only so the table is complete and the indices above are pinned down by
		// something on both sides. The SDK header itself says to prefer the P2P functions
		// and that these "will be removed eventually". DO NOT CALL ANY OF THESE.
		//
		// Note these take uint32 nIP, which is the 005 signature. SteamNetworking006 and
		// later replaced those with SteamIPAddress_t, which is a larger struct and would
		// change the stack layout. Another reason not to touch them.

		virtual SNetListenSocket_t CreateListenSocket(int nVirtualP2PPort, uint32 nIP, uint16 nPort,
		    bool bAllowUseOfPacketRelay) = 0; // 8
		virtual SNetSocket_t CreateP2PConnectionSocket(uint64 steamIDTarget, int nVirtualPort,
		    int nTimeoutSec, bool bAllowUseOfPacketRelay) = 0;                                      // 9
		virtual SNetSocket_t CreateConnectionSocket(uint32 nIP, uint16 nPort, int nTimeoutSec) = 0; // 10
		virtual bool DestroySocket(SNetSocket_t hSocket, bool bNotifyRemoteEnd) = 0;                // 11
		virtual bool DestroyListenSocket(SNetListenSocket_t hSocket, bool bNotifyRemoteEnd) = 0;    // 12
		virtual bool SendDataOnSocket(SNetSocket_t hSocket, void* pubData, uint32 cubData,
		    bool bReliable) = 0;                                                             // 13
		virtual bool IsDataAvailableOnSocket(SNetSocket_t hSocket, uint32* pcubMsgSize) = 0; // 14
		virtual bool RetrieveDataFromSocket(SNetSocket_t hSocket, void* pubDest, uint32 cubDest,
		    uint32* pcubMsgSize) = 0; // 15
		virtual bool IsDataAvailable(SNetListenSocket_t hListenSocket, uint32* pcubMsgSize,
		    SNetSocket_t* phSocket) = 0; // 16
		virtual bool RetrieveData(SNetListenSocket_t hListenSocket, void* pubDest, uint32 cubDest,
		    uint32* pcubMsgSize, SNetSocket_t* phSocket) = 0; // 17
		virtual bool GetSocketInfo(SNetSocket_t hSocket, SteamId* pSteamIDRemote, int* peSocketStatus,
		    uint32* punIPRemote, uint16* punPortRemote) = 0; // 18
		virtual bool GetListenSocketInfo(SNetListenSocket_t hListenSocket, uint32* pnIP,
		    uint16* pnPort) = 0;                                       // 19
		virtual int GetSocketConnectionType(SNetSocket_t hSocket) = 0; // 20
		virtual int GetMaxPacketSize(SNetSocket_t hSocket) = 0;        // 21
	};

	// Slot indices as named constants, for anyone building a thunk by hand or eyeballing a
	// vtable in a debugger. Same provenance as the class above.
	enum
	{
		k_iSlot_SendP2PPacket = 0,
		k_iSlot_IsP2PPacketAvailable = 1,
		k_iSlot_ReadP2PPacket = 2,
		k_iSlot_AcceptP2PSessionWithUser = 3,
		k_iSlot_CloseP2PSessionWithUser = 4,
		k_iSlot_CloseP2PChannelWithUser = 5,
		k_iSlot_GetP2PSessionState = 6,
		k_iSlot_AllowP2PPacketRelay = 7,
		// 8 to 21 are the legacy socket API, see the class body.
		k_iSlot_CreateListenSocket = 8,
		k_iSlot_CreateP2PConnectionSocket = 9,
		k_iSlot_CreateConnectionSocket = 10,
		k_iSlot_DestroySocket = 11,
		k_iSlot_DestroyListenSocket = 12,
		k_iSlot_SendDataOnSocket = 13,
		k_iSlot_IsDataAvailableOnSocket = 14,
		k_iSlot_RetrieveDataFromSocket = 15,
		k_iSlot_IsDataAvailable = 16,
		k_iSlot_RetrieveData = 17,
		k_iSlot_GetSocketInfo = 18,
		k_iSlot_GetListenSocketInfo = 19,
		k_iSlot_GetSocketConnectionType = 20,
		k_iSlot_GetMaxPacketSize = 21,
		k_nSteamNetworking005VtableSlots = 22
	};

	// ---------------------------------------------------------------------------
	// Raw __thiscall thunks, as an alternative to the class above.
	//
	// You should normally just use ISteamNetworking005. These exist because the task of
	// writing a thunk by hand is exactly where the ABI goes wrong, so here is the correct
	// spelling once, written down.
	//
	// MSVC does allow __thiscall on a function pointer type for x86, and the convention is
	// "this in ECX, remaining arguments pushed right to left, callee pops". Declare the
	// interface pointer as the FIRST parameter and MSVC puts it in ECX for you.
	//
	// [S3] verified these are equivalent. Compiling
	//
	//     void **vt = *reinterpret_cast<void ***>( iface );
	//     FnSendP2PPacket fn = reinterpret_cast<FnSendP2PPacket>( vt[0] );
	//     return fn( iface, id, data, len, 2, 0 );
	//
	// produced the identical instruction sequence to the virtual call quoted in the
	// CSteamID block above: same ECX load, same six pushes in the same order, same
	// "ret 0" with no caller stack fixup.
	// ---------------------------------------------------------------------------

	typedef bool(__thiscall* FnSendP2PPacket)(void* self, uint64 steamIDRemote, const void* pubData,
	    uint32 cubData, int eP2PSendType, int nChannel);
	typedef bool(__thiscall* FnIsP2PPacketAvailable)(void* self, uint32* pcubMsgSize, int nChannel);
	typedef bool(__thiscall* FnReadP2PPacket)(void* self, void* pubDest, uint32 cubDest,
	    uint32* pcubMsgSize, SteamId* psteamIDRemote, int nChannel);
	typedef bool(__thiscall* FnAcceptP2PSessionWithUser)(void* self, uint64 steamIDRemote);
	typedef bool(__thiscall* FnCloseP2PSessionWithUser)(void* self, uint64 steamIDRemote);
	typedef bool(__thiscall* FnCloseP2PChannelWithUser)(void* self, uint64 steamIDRemote, int nChannel);
	typedef bool(__thiscall* FnGetP2PSessionState)(void* self, uint64 steamIDRemote,
	    P2PSessionState_t* pConnectionState);
	typedef bool(__thiscall* FnAllowP2PPacketRelay)(void* self, bool bAllow);

	// Pull slot n out of an interface pointer. No type safety, so prefer the class.
	inline void* SteamVtableSlot(void* iface, int slot)
	{
		return (*reinterpret_cast<void***>(iface))[slot];
	}

	// ---------------------------------------------------------------------------
	// ISteamClient016 - just the slot indices we might need.
	//
	// Provenance: [S1] steamworks_sdk_131/isteamclient.h, which is the SDK whose
	// STEAMCLIENT_INTERFACE_VERSION is exactly the "SteamClient016" string in the game's
	// DLL, so this is the right revision and not a near miss. Counting the virtuals in
	// declaration order from 0 puts GetISteamGenericInterface at 12 and
	// GetISteamNetworking at 16. [S2] ISteamClient016.h, reverse engineered from the
	// shipping steamclient.dll, gives the same two indices. Two independent sources agree.
	//
	// WHY THE VERSION MATTERS SO MUCH HERE, as a warning: in the older SteamClient009 this
	// interface had GetISteamMasterServerUpdater at slot 11, which was later removed. That
	// shifts GetISteamGenericInterface from 13 down to 12. So an isteamclient.h grabbed
	// from a random SDK will give you an index that is wrong by one, and a vtable index
	// that is wrong by one is a call into GetISteamMatchmakingServers with a mismatched
	// argument list. Only use indices verified against SteamClient016.
	//
	// HONEST LIMIT ON THIS BLOCK: slots 0 through 22 are identical between [S1] and [S2].
	// From slot 23 up they DISAGREE - Valve's 1.31 header has GetISteamPS3OverlayRender at
	// 23 while open-steamworks' ISteamClient016 goes straight to GetISteamHTTP. I did not
	// resolve that, and I did not need to. Treat any ISteamClient016 slot >= 23 as
	// UNVERIFIED and go re-derive it before calling it.
	// ---------------------------------------------------------------------------

	enum
	{
		k_iSlot_SteamClient016_GetISteamGenericInterface = 12,
		k_iSlot_SteamClient016_GetISteamNetworking = 16
	};

	// Signatures for those two slots. HSteamUser and HSteamPipe come from the
	// GetHSteamUser and GetHSteamPipe exports, see the export block below.
	//
	// GetISteamGenericInterface is the escape hatch: it takes any interface version string
	// and hands back the matching object, so it is how you would reach an interface that
	// steam_api.dll has no dedicated export for. That is the route to a modern
	// ISteamNetworkingSockets if we ever want one.
	//
	// BUT, and this is the part that is not an ABI question: the shipped steam_api.dll only
	// contains the version string "SteamNetworking005". The newer interfaces are
	// implemented in the installed Steam client's steamclient.dll, so whether asking this
	// pipe for "SteamNetworkingSockets012" actually returns a non-null pointer is an
	// empirical question about the running client, not something this header can answer.
	// Check the return for null and have a fallback. The vtable layout of whatever it
	// returns is also NOT described in this file - do not call into it on the strength of
	// having a pointer.
	typedef void*(__thiscall* FnGetISteamGenericInterface)(void* self, HSteamUser hSteamUser,
	    HSteamPipe hSteamPipe, const char* pchVersion);
	typedef void*(__thiscall* FnGetISteamNetworking)(void* self, HSteamUser hSteamUser,
	    HSteamPipe hSteamPipe, const char* pchVersion);

	// ---------------------------------------------------------------------------
	// RETURNING A CSteamID BY VALUE - read this before touching GetSteamID or
	// GetFriendByIndex.
	//
	// An 8-byte class or struct return value on 32-bit MSVC is NOT returned in the
	// EAX:EDX register pair. It is returned through a hidden return-buffer pointer: the
	// CALLER allocates an 8-byte temporary, passes its address as an extra invisible
	// argument pushed on the stack, and the callee fills that buffer in and returns the
	// same pointer back in EAX.
	//
	// A raw uint64 return, by contrast, DOES come back in EAX:EDX with no buffer at all.
	// These are two completely different conventions. So declaring GetSteamID as returning
	// uint64 is NOT a harmless simplification the way it was for CSteamID *parameters* - it
	// is wrong, it leaves the stack unbalanced and it reads the result from the wrong place.
	// This is the one asymmetry in this header: for arguments, uint64 and CSteamID are
	// interchangeable, and for RETURN VALUES they are not.
	//
	// [S3] was asked directly. Three variants were compiled, all 8 bytes:
	//   (A) CSteamID as the SDK declares it, pack(1), with user-declared constructors
	//   (B) a trivial pack(1) POD struct holding one uint64, no constructors
	//   (C) a plain uint64
	//
	// (A) and (B) produced BYTE-IDENTICAL code, so whether the type has constructors makes
	// no difference at this size. (C) was completely different. For (A) and (B):
	//
	//     mov  ecx, DWORD PTR _p$[esp-4]   ; this -> ECX
	//     lea  edx, DWORD PTR $T1[esp]     ; address of the caller's 8-byte temporary
	//     sub  esp, 8                      ; reserve that temporary
	//     mov  eax, DWORD PTR [ecx]        ; vtable
	//     push edx                         ; HIDDEN return-buffer pointer
	//     call DWORD PTR [eax]             ; slot 0
	//     mov  edx, eax                    ; callee handed the buffer pointer back in EAX
	//     mov  eax, DWORD PTR [edx]        ; low dword
	//     mov  edx, DWORD PTR [edx+4]      ; high dword
	//     add  esp, 8
	//     ret  0                           ; callee popped the hidden pointer
	//
	// whereas (C), the uint64 version, was just:
	//
	//     mov  ecx, DWORD PTR _p$[esp-4]
	//     mov  eax, DWORD PTR [ecx]
	//     mov  eax, DWORD PTR [eax]
	//     jmp  eax                         ; tail call, result already in EAX:EDX
	//
	// WHAT THIS MEANS FOR HOW YOU DECLARE IT. Because variant (B) - a trivial pack(1) POD
	// holding a uint64, which is exactly our SteamId type - generates identical code to the
	// real CSteamID, declaring these methods as returning SteamId is correct. That is what
	// the two interfaces below do, and then MSVC sets up the hidden buffer for you and you
	// never have to think about it again. Just call it and use the result.
	//
	// If you ever hand-roll a thunk for one of these, the hidden pointer has to be spelled
	// out explicitly as the first parameter after self, and the return type is the pointer:
	//
	//     typedef SteamId *(__thiscall *FnGetSteamID)( void *self, SteamId *pRetBuf );
	//
	// Where the method also takes real arguments, the hidden buffer pointer comes FIRST,
	// before them, in the argument list. [S3] confirmed the ordering on GetFriendByIndex,
	// see the note in the ISteamFriends014 block below.
	// ---------------------------------------------------------------------------

	// ---------------------------------------------------------------------------
	// ISteamUser017 - this is how a player learns their OWN SteamID.
	//
	// Needed because, with the no-callback design, a client must know the host's SteamID
	// before it can send its first packet, and nothing in the process could otherwise tell
	// a player their own id to pass on.
	//
	// Provenance: [S1] steamworks_sdk_131/isteamuser.h, class ISteamUser, with
	// "#define STEAMUSER_INTERFACE_VERSION "SteamUser017"" at line 208. SDK 1.31 is the
	// right tree: its STEAMCLIENT_INTERFACE_VERSION is SteamClient016, its
	// STEAMUSER_INTERFACE_VERSION is SteamUser017, its STEAMFRIENDS_INTERFACE_VERSION is
	// SteamFriends014 and its STEAMNETWORKING_INTERFACE_VERSION is SteamNetworking005. All
	// four match the strings in the game's DLL, so the whole header set is consistent and
	// this is not a near miss. isteamuser.h is also byte-identical across SDK 1.28 to 1.31
	// (md5 b406ee3d5f340c1401616d8a0bb79abe), so SteamUser017 is stable over that window.
	//
	// Corroborated by [S2] open-steamworks ISteamUser017.h, reverse engineered from the
	// shipping steamclient.dll, which lists the same methods in the same order.
	//
	// No overloaded virtual names in this interface, so declaration order is vtable order
	// and the MSVC overload-group reversal does not apply. I checked for duplicate method
	// names explicitly rather than assuming.
	//
	// Only the first three slots are declared here. That is deliberate: slots 3 and up are
	// game-connection, voice and auth-ticket machinery we have no use for, and declaring
	// them would mean getting a dozen more signatures right for no benefit. The three we
	// need are the first three, which is a nice accident.
	//
	// HONEST NOTE ON THE TOTAL SLOT COUNT, since someone will eventually want to extend
	// this: on Windows this interface has 24 slots, 0 through 23, ending at
	// GetPlayerSteamLevel. The four methods that appear after it in the header
	// (LogOn, LogOnAndLinkSteamAccountToPSN, LogOnAndCreateNewSteamAccountIfNeeded,
	// GetConsoleSteamID) are inside a "#ifdef _PS3" block, [S1] isteamuser.h lines 169-204,
	// so they do NOT exist in the Windows vtable. Counting virtuals in the file without
	// noticing that ifdef gives you 28 and a wrong idea of the table.
	// ---------------------------------------------------------------------------

	class ISteamUser017
	{
	public:
		// Slot 0. The handle this interface is bound to. Not usually needed, since the
		// GetHSteamUser export gives you the same thing.
		virtual HSteamUser GetHSteamUser() = 0;

		// Slot 1. True once the user is logged on to Steam and the id below is meaningful.
		// CHECK THIS FIRST. If it returns false, GetSteamID has nothing real to give you,
		// so refuse politely instead of handing a garbage id to the player to paste.
		virtual bool BLoggedOn() = 0;

		// Slot 2. The local user's own SteamID.
		//
		// Returns by value through a hidden buffer, see the long block above. Declared as
		// SteamId because a trivial 8-byte POD and the real CSteamID compile to the same
		// convention, verified. Just call it:
		//
		//     workshop::SteamId me = user->GetSteamID();
		//     uint64 raw = me.m_unAll64Bits;      // the 17-digit number players share
		//
		// Do NOT redeclare this as returning uint64. That changes the convention from a
		// hidden stack buffer to EAX:EDX and corrupts the call.
		virtual SteamId GetSteamID() = 0;

		// Slots 3 to 23 intentionally not declared. See the block comment above. If you add
		// any, you must declare EVERY preceding slot so the indices stay right, and you
		// must re-verify against SDK 1.31 isteamuser.h.
	};

	enum
	{
		k_iSlot_SteamUser017_GetHSteamUser = 0,
		k_iSlot_SteamUser017_BLoggedOn = 1,
		k_iSlot_SteamUser017_GetSteamID = 2,
		k_nSteamUser017VtableSlotsWindows = 24 // 0..23, PS3-only tail excluded
	};

	// Hand-rolled forms, if you want them. Note GetSteamID's hidden return buffer.
	typedef bool(__thiscall* FnBLoggedOn)(void* self);
	typedef SteamId*(__thiscall* FnGetSteamID)(void* self, SteamId* pRetBuf);

	// ---------------------------------------------------------------------------
	// ISteamFriends014 - optional "pick a friend from a list" instead of pasting a
	// 17-digit number.
	//
	// Verdict up front, since this was asked as a "say no if the evidence is thin": the
	// evidence is NOT thin. These three slots are pinnable to the same standard as the
	// networking table, and they are all in the first eight slots.
	//
	// Provenance: [S1] steamworks_sdk_131/isteamfriends.h, class ISteamFriends, with
	// "#define STEAMFRIENDS_INTERFACE_VERSION "SteamFriends014"", which is the string in
	// the game's DLL. Corroborated by [S2] open-steamworks ISteamFriends014.h, reverse
	// engineered from the shipping DLL, which gives the identical first eight slots.
	// No overloaded virtual names, checked explicitly, and no #ifdef anywhere inside the
	// class body, so there is no conditional-compilation hazard like ISteamUser017 has.
	//
	// As with ISteamUser017 only the slots we need are declared, and the padding slots in
	// between are declared too because they have to be, to keep the indices correct. The
	// padding ones are marked DO NOT CALL - their signatures are copied from [S1] and are
	// almost certainly right, but they are unexercised and there is no reason to touch them.
	// ---------------------------------------------------------------------------

	class ISteamFriends014
	{
	public:
		// Slot 0. The local user's own display name, UTF-8. See the string lifetime warning
		// below, it applies to every const char * on this interface.
		virtual const char* GetPersonaName() = 0;

		virtual SteamAPICall_t SetPersonaName(const char* pchPersonaName) = 0; // 1, DO NOT CALL
		virtual int GetPersonaState() = 0;                                     // 2, EPersonaState

		// Slot 3. How many users the client knows about matching iFriendFlags. Pass
		// k_EFriendFlagImmediate for "regular friends", which is what a friend picker wants.
		// Returns -1 if the flags are invalid, so treat a negative result as an error and
		// not as a count.
		virtual int GetFriendCount(int iFriendFlags) = 0;

		// Slot 4. The friend at iFriend, which must be in [0, GetFriendCount(flags)). Pass
		// the SAME iFriendFlags you passed to GetFriendCount, or the indices do not line up.
		//
		// Returns a SteamID by value, so it uses the hidden return buffer convention, same
		// as GetSteamID. [S3] confirmed where the hidden pointer sits when there are also
		// real arguments: it goes FIRST, ahead of iFriend and iFriendFlags. The class
		// declaration below handles that for you.
		virtual SteamId GetFriendByIndex(int iFriend, int iFriendFlags) = 0;

		virtual int GetFriendRelationship(uint64 steamIDFriend) = 0; // 5, DO NOT CALL
		virtual int GetFriendPersonaState(uint64 steamIDFriend) = 0; // 6, DO NOT CALL

		// Slot 7. A friend's display name, UTF-8.
		//
		// TWO CAVEATS, both from [S1]'s own comments and both of which will produce a
		// confusing friend picker if ignored.
		//
		// 1. STRING LIFETIME. The header says of these char * returns: "it's important that
		//    this pointer is not saved off; it will eventually be free'd or re-allocated".
		//    So copy the bytes into your own buffer immediately. Do not store the pointer,
		//    do not hold it across another Steam call, do not hand it to the UI to keep.
		//
		// 2. THE NAME MAY NOT BE KNOWN YET. The header warns that "on first joining a
		//    lobby, chat room or game server the local user will not known the name of the
		//    other users automatically; that information will arrive asyncronously". For the
		//    user's own friends list this is normally fine, because Steam already has those
		//    names, but handle an empty string rather than assuming a name is always there.
		virtual const char* GetFriendPersonaName(uint64 steamIDFriend) = 0;

		// Slots 8 and up intentionally not declared. Same rule as ISteamUser017: if you add
		// any, declare every preceding slot and re-verify against SDK 1.31.
	};

	enum
	{
		k_iSlot_SteamFriends014_GetPersonaName = 0,
		k_iSlot_SteamFriends014_GetFriendCount = 3,
		k_iSlot_SteamFriends014_GetFriendByIndex = 4,
		k_iSlot_SteamFriends014_GetFriendPersonaName = 7
	};

	// EFriendFlags. Provenance: [S1] steamworks_sdk_131/isteamfriends.h lines 65-78.
	// k_EFriendFlagImmediate is the one you want for a friend picker, the header calls it
	// the "regular" friend.
	enum
	{
		k_EFriendFlagNone = 0x00,
		k_EFriendFlagBlocked = 0x01,
		k_EFriendFlagFriendshipRequested = 0x02,
		k_EFriendFlagImmediate = 0x04, // "regular" friend, use this one
		k_EFriendFlagClanMember = 0x08,
		k_EFriendFlagOnGameServer = 0x10,
		k_EFriendFlagRequestingFriendship = 0x80,
		k_EFriendFlagRequestingInfo = 0x100,
		k_EFriendFlagIgnored = 0x200,
		k_EFriendFlagIgnoredFriend = 0x400,
		k_EFriendFlagSuggested = 0x800,
		k_EFriendFlagAll = 0xFFFF
	};

	// EPersonaState. Provenance: [S1] isteamfriends.h. Only useful if you want to grey out
	// offline friends in a picker.
	enum
	{
		k_EPersonaStateOffline = 0,
		k_EPersonaStateOnline = 1,
		k_EPersonaStateBusy = 2,
		k_EPersonaStateAway = 3,
		k_EPersonaStateSnooze = 4,
		k_EPersonaStateLookingToTrade = 5,
		k_EPersonaStateLookingToPlay = 6
	};

	// ---------------------------------------------------------------------------
	// CCallbackBase, for SteamAPI_RegisterCallback.
	//
	// Provenance: [S1] steamworks_sdk_131/steam_api.h, class CCallbackBase at line 162,
	// which in full is:
	//
	//     class CCallbackBase
	//     {
	//     public:
	//         CCallbackBase() { m_nCallbackFlags = 0; m_iCallback = 0; }
	//         // don't add a virtual destructor because we export this binary interface across dll's
	//         virtual void Run( void *pvParam ) = 0;
	//         virtual void Run( void *pvParam, bool bIOFailure, SteamAPICall_t hSteamAPICall ) = 0;
	//         int GetICallback() { return m_iCallback; }
	//         virtual int GetCallbackSizeBytes() = 0;
	//     protected:
	//         enum { k_ECallbackFlagsRegistered = 0x01, k_ECallbackFlagsGameServer = 0x02 };
	//         uint8 m_nCallbackFlags;
	//         int m_iCallback;
	//         friend class CCallbackMgr;
	//     };
	//
	// Note GetICallback is NOT virtual, so it takes no vtable slot. There are exactly
	// three virtual slots. There is deliberately no virtual destructor.
	//
	// *** THE ONE THING IN THIS FILE MOST LIKELY TO GET SOMEONE KILLED ***
	//
	// Run is OVERLOADED. MSVC does not emit an overload group in declaration order, it
	// emits it in REVERSE declaration order. So the vtable is NOT
	// [Run(void*), Run(void*,bool,uint64), GetCallbackSizeBytes]. [S3] was asked directly,
	// by giving the two overloads distinguishable bodies and reading the mangled names out
	// of the real object file:
	//
	//     ??_7MyCb@@6B@ DD FLAT:??_R4MyCb@@6B@        ; MyCb::`vftable'
	//         DD FLAT:?Run@MyCb@@UAEXPAX_N_K@Z        ; slot 0
	//         DD FLAT:?Run@MyCb@@UAEXPAX@Z            ; slot 1
	//         DD FLAT:?GetCallbackSizeBytes@MyCb@@UAEHXZ ; slot 2
	//
	// Decoding the mangling: "PAX_N_K" is (void*, bool, unsigned __int64) and plain "PAX"
	// is (void*). So the REAL layout is
	//
	//     slot 0 : Run( void *pvParam, bool bIOFailure, SteamAPICall_t hSteamAPICall )  <- 3 args
	//     slot 1 : Run( void *pvParam )                                                <- 1 arg
	//     slot 2 : GetCallbackSizeBytes()
	//
	// The three-argument call-result form is FIRST and the one-argument plain-callback form
	// is SECOND. The ordinary callback we care about, P2PSessionRequest_t, is delivered
	// through slot 1, not slot 0.
	//
	// And the object layout, also from [S3]:
	//
	//     class CCallbackBase  size(12):
	//      0   | {vfptr}
	//      4   | m_nCallbackFlags
	//          | <alignment member> (size=3)
	//      8   | m_iCallback
	//
	// so vtable pointer at +0, uint8 m_nCallbackFlags at +4 with three bytes of padding,
	// int m_iCallback at +8, total 12 bytes. steam_api.h has no #pragma pack anywhere, so
	// this is default packing.
	//
	// THE SAFE WAY TO BUILD ONE, and the reason the struct below looks like it does: if you
	// declare the two overloads in the SDK's own declaration order, MSVC applies the same
	// reversal to your class that it applied to Valve's, so your vtable matches what
	// steam_api.dll expects. The reversal cancels out. So DECLARE THEM IN SDK ORDER AND DO
	// NOT "FIX" THE ORDER. The only situation where you must hand-write the reversed order
	// is if you build the vtable yourself as an explicit array of function pointers, in
	// which case the array literal has to be
	// { Run_threeArg, Run_oneArg, GetCallbackSizeBytes }.
	//
	// Two more things that are preconditions, not decoration:
	//   - m_nCallbackFlags and m_iCallback must be initialised before you register.
	//     SteamAPI_RegisterCallback sets k_ECallbackFlagsRegistered in m_nCallbackFlags
	//     itself, so start it at 0 and set m_iCallback to the k_iCallback you are
	//     registering for.
	//   - Callbacks are only dispatched from inside SteamAPI_RunCallbacks, which the GAME
	//     calls on its own thread. So Run fires on whatever thread the game pumps Steam
	//     from. Do not touch game state from in there without thinking about it, just
	//     record the event and handle it on our own tick.
	//   - Unregister before the object dies. A registered CCallbackBase that gets freed
	//     leaves steam_api.dll holding a dangling pointer it will call later.
	//
	// CONFIDENCE: the layout and the slot order above are verified, the first from Valve's
	// own header and the second from the real compiler. What is NOT verified by experiment
	// is that the shipped steam_api.dll dispatches through these slots as expected at
	// runtime, because that needs the game running. The layout is right. The behaviour is
	// consistent with the header it was built from, but it is an inference until someone
	// runs it.
	//
	// *** RECOMMENDED ALTERNATIVE: DO NOT USE CALLBACKS AT ALL ***
	//
	// For Al Bhed Workshop specifically, we do not need any of this. We already know every
	// peer's SteamID before the session starts, because that is how we set the session up.
	// The SDK header for AcceptP2PSessionWithUser states that calling SendP2PPacket to a
	// peer implicitly accepts that peer's pending session request, and that
	// AcceptP2PSessionWithUser may be called more than once for the same user harmlessly.
	// So have every peer proactively call AcceptP2PSessionWithUser on every other peer at
	// session start, and then just poll IsP2PPacketAvailable / ReadP2PPacket on our own
	// tick. That needs zero callback registration, no hand-rolled vtable, no lifetime
	// problem and no thread question, and it removes the single most fragile thing in this
	// header from our attack surface. With at most 3 players it costs 2 extra calls per
	// peer. Take this route. Use the struct below only if something later genuinely
	// requires a real callback.
	// ---------------------------------------------------------------------------

	// Flags from [S1] steam_api.h line 173.
	enum
	{
		k_ECallbackFlagsRegistered = 0x01,
		k_ECallbackFlagsGameServer = 0x02
	};

	// Worked, compilable, SDK-free CCallbackBase. Declaration order below is the SDK's
	// order on purpose. See the long comment above before changing anything here.
	//
	// Usage:
	//     workshop::SteamCallbackShim g_onSessionRequest;
	//     g_onSessionRequest.Init( workshop::P2PSessionRequest_t::k_iCallback,
	//                              sizeof( workshop::P2PSessionRequest_t ),
	//                              &MyHandler );
	//     SteamAPI_RegisterCallback( (void *)&g_onSessionRequest,
	//                                workshop::P2PSessionRequest_t::k_iCallback );
	//     ... later, before it is destroyed ...
	//     SteamAPI_UnregisterCallback( (void *)&g_onSessionRequest );
	class SteamCallbackShim
	{
	public:
		typedef void (*Handler)(void* pvParam);

		SteamCallbackShim()
		    : m_nCallbackFlags(0), m_iCallback(0), m_cbSize(0), m_pfnHandler(0)
		{
		}

		void Init(int iCallback, int cbCallbackSize, Handler pfn)
		{
			m_iCallback = iCallback;
			m_cbSize = cbCallbackSize;
			m_pfnHandler = pfn;
			// Leave m_nCallbackFlags alone. SteamAPI_RegisterCallback ORs in
			// k_ECallbackFlagsRegistered and SteamAPI_UnregisterCallback clears it.
		}

		bool IsRegistered() const
		{
			return (m_nCallbackFlags & k_ECallbackFlagsRegistered) != 0;
		}

		// Compile-time layout check. It lives as a member function because the two fields
		// it checks are protected, and because offsetof needs the class to be complete, so
		// the body is defined just below the class. Never called at runtime.
		static void AbiSelfCheck();

		// --- the three virtual slots, in SDK DECLARATION order. MSVC reverses the two
		// --- Run overloads for us, which is what makes this match the DLL. Do not reorder.

		// Ends up in vtable slot 1. This is the one ordinary callbacks arrive on.
		virtual void Run(void* pvParam)
		{
			if (m_pfnHandler)
				m_pfnHandler(pvParam);
		}

		// Ends up in vtable slot 0. This is the CallResult form, used by
		// SteamAPI_RegisterCallResult. We do not use call results, but the slot must exist
		// and must be safe to call, so forward the non-failure case and swallow the rest.
		virtual void Run(void* pvParam, bool bIOFailure, SteamAPICall_t hSteamAPICall)
		{
			(void)hSteamAPICall;
			if (!bIOFailure && m_pfnHandler)
				m_pfnHandler(pvParam);
		}

		// Ends up in vtable slot 2. Steam uses this to size the buffer it hands to Run, so
		// returning the wrong number here means Steam copies the wrong number of bytes.
		// It must be sizeof the callback struct you registered for, which is why Init takes
		// it rather than guessing. For P2PSessionRequest_t that is 8 and for
		// P2PSessionConnectFail_t it is 9.
		virtual int GetCallbackSizeBytes()
		{
			return m_cbSize;
		}

	protected:
		// Offsets +0 vfptr, +4 m_nCallbackFlags, +8 m_iCallback must match CCallbackBase
		// exactly, because steam_api.dll reads these two fields directly. The static_assert
		// block at the end of this file enforces it. Anything we add must come AFTER
		// m_iCallback.
		uint8 m_nCallbackFlags; // +4
		int m_iCallback;        // +8

		// Our own additions, past the end of the ABI-visible part.
		int m_cbSize;         // +12
		Handler m_pfnHandler; // +16
	};

	// The ABI-visible prefix of our shim has to line up with CCallbackBase: vfptr at +0,
	// m_nCallbackFlags at +4, m_iCallback at +8. steam_api.dll reads those two fields
	// directly, so if this ever drifts the DLL reads garbage.
	inline void SteamCallbackShim::AbiSelfCheck()
	{
		static_assert(offsetof(SteamCallbackShim, m_nCallbackFlags) == 4,
		    "m_nCallbackFlags must sit at +4 like CCallbackBase");
		static_assert(offsetof(SteamCallbackShim, m_iCallback) == 8,
		    "m_iCallback must sit at +8 like CCallbackBase");
	}

	// ---------------------------------------------------------------------------
	// steam_api.dll exports we rely on.
	//
	// Provenance: [S1] steamworks_sdk_131/steam_api.h for the declarations, plus
	// steamtypes.h line 13 for "#define S_CALLTYPE __cdecl" and steam_api.h line 41 for
	// "#define S_API extern "C"". So every one of these is extern "C" __cdecl, NOT
	// __stdcall. All of these names were confirmed present in the game's DLL export dump.
	//
	// Relevant declarations as they appear in [S1] steam_api.h:
	//     S_API ISteamNetworking *S_CALLTYPE SteamNetworking();            // line 119
	//     S_API ISteamClient     *S_CALLTYPE SteamClient();                // line 90
	//     S_API HSteamUser  GetHSteamUser();                               // line 378
	//     S_API HSteamPipe  GetHSteamPipe();                               // line 377
	//     S_API HSteamUser  SteamAPI_GetHSteamUser();                      // line 389
	//     S_API HSteamPipe  SteamAPI_GetHSteamPipe();                      // line 371
	//     S_API void S_CALLTYPE SteamAPI_RunCallbacks();                   // line 146
	//     S_API void S_CALLTYPE SteamAPI_RegisterCallback( class CCallbackBase *pCallback,
	//                                                      int iCallback ); // line 151
	//     S_API void S_CALLTYPE SteamAPI_UnregisterCallback( class CCallbackBase *pCallback ); // line 152
	//
	// IMPORTANT: SteamNetworking() returns the interface the GAME already initialised. The
	// game calls SteamAPI_Init itself, so we must NOT call SteamAPI_Init or
	// SteamAPI_Shutdown. We also should not call SteamAPI_RunCallbacks on our own schedule
	// if the game is already pumping it. Resolve these by name with GetProcAddress on the
	// already-loaded steam_api.dll rather than linking an import library.
	//
	// CCallbackBase * is spelled void * here so this block needs no SDK types. Pass the
	// address of a SteamCallbackShim.
	// ---------------------------------------------------------------------------

	typedef void*(__cdecl* FnSteamNetworking)();
	typedef void*(__cdecl* FnSteamClient)();
	// SteamUser and SteamFriends are direct exports of the shipped DLL too, same shape as
	// SteamNetworking: extern "C" __cdecl, no arguments, returning the already-initialised
	// interface. [S1] steam_api.h declares them as
	//     S_API ISteamUser    *S_CALLTYPE SteamUser();
	//     S_API ISteamFriends *S_CALLTYPE SteamFriends();
	// Cast the result to ISteamUser017 * / ISteamFriends014 *. Null-check both: they return
	// null if the game has not called SteamAPI_Init yet.
	typedef void*(__cdecl* FnSteamUser)();
	typedef void*(__cdecl* FnSteamFriends)();
	typedef HSteamUser(__cdecl* FnGetHSteamUser)();
	typedef HSteamPipe(__cdecl* FnGetHSteamPipe)();
	typedef void(__cdecl* FnSteamAPI_RunCallbacks)();
	typedef void(__cdecl* FnSteamAPI_RegisterCallback)(void* pCallback, int iCallback);
	typedef void(__cdecl* FnSteamAPI_UnregisterCallback)(void* pCallback);

// The interface version string in the shipped DLL. Only needed if you go through
// ISteamClient016::GetISteamGenericInterface instead of the SteamNetworking export.
// Provenance: [S1] isteamnetworking.h line 262, and it is the only networking version
// string present in the game's steam_api.dll.
#define WORKSHOP_STEAMNETWORKING_INTERFACE_VERSION "SteamNetworking005"
#define WORKSHOP_STEAMCLIENT_INTERFACE_VERSION "SteamClient016"
#define WORKSHOP_STEAMUSER_INTERFACE_VERSION "SteamUser017"
#define WORKSHOP_STEAMFRIENDS_INTERFACE_VERSION "SteamFriends014"

	// ---------------------------------------------------------------------------
	// Self-checks. These cost nothing at runtime and they turn a silent ABI drift into a
	// compile error. Every number here was read out of the real compiler, see [S3].
	// ---------------------------------------------------------------------------

#define WORKSHOP_STEAM_ABI_CHECK(cond, msg) static_assert(cond, msg)

	WORKSHOP_STEAM_ABI_CHECK(sizeof(void*) == 4,
	    "SteamAbi.h is for 32-bit only");

	WORKSHOP_STEAM_ABI_CHECK(sizeof(SteamId) == 8,
	    "SteamId must be 8 bytes to stand in for CSteamID");

	WORKSHOP_STEAM_ABI_CHECK(sizeof(P2PSessionState_t) == 20,
	    "P2PSessionState_t must be 20 bytes");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_bConnectionActive) == 0, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_bConnecting) == 1, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_eP2PSessionError) == 2, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_bUsingRelay) == 3, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_nBytesQueuedForSend) == 4, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_nPacketsQueuedForSend) == 8, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_nRemoteIP) == 12, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionState_t, m_nRemotePort) == 16, "");

	// 8 and 9, not 8 and 16. See the callback block above for why the pack(1) on SteamId
	// is what makes this come out right.
	WORKSHOP_STEAM_ABI_CHECK(sizeof(P2PSessionRequest_t) == 8,
	    "P2PSessionRequest_t must be 8 bytes, GetCallbackSizeBytes depends on it");
	WORKSHOP_STEAM_ABI_CHECK(sizeof(P2PSessionConnectFail_t) == 9,
	    "P2PSessionConnectFail_t must be 9 bytes, not 12 and not 16");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionConnectFail_t, m_steamIDRemote) == 0, "");
	WORKSHOP_STEAM_ABI_CHECK(offsetof(P2PSessionConnectFail_t, m_eP2PSessionError) == 8, "");

	WORKSHOP_STEAM_ABI_CHECK((int)P2PSessionRequest_t::k_iCallback == 1202,
	    "P2PSessionRequest_t callback id must be 1202");
	WORKSHOP_STEAM_ABI_CHECK((int)P2PSessionConnectFail_t::k_iCallback == 1203,
	    "P2PSessionConnectFail_t callback id must be 1203");

	// The CCallbackBase prefix check lives in SteamCallbackShim::AbiSelfCheck above,
	// because the fields it checks are protected.

	WORKSHOP_STEAM_ABI_CHECK((int)k_EP2PSendReliable == 2,
	    "k_EP2PSendReliable must be 2");

	WORKSHOP_STEAM_ABI_CHECK((int)k_EFriendFlagImmediate == 0x04,
	    "k_EFriendFlagImmediate must be 0x04, it is what a friend picker passes");

	// The return-value interfaces are 4 bytes, just a vtable pointer, like every other
	// Steam interface. If one of these ever came out larger it would mean a stray data
	// member crept into the declaration and every slot index below it would be suspect.
	WORKSHOP_STEAM_ABI_CHECK(sizeof(ISteamUser017) == 4,
	    "ISteamUser017 must be just a vtable pointer");
	WORKSHOP_STEAM_ABI_CHECK(sizeof(ISteamFriends014) == 4,
	    "ISteamFriends014 must be just a vtable pointer");
	WORKSHOP_STEAM_ABI_CHECK(sizeof(ISteamNetworking005) == 4,
	    "ISteamNetworking005 must be just a vtable pointer");

	// GetSteamID and GetFriendByIndex return this by value through a hidden buffer. The
	// convention was verified for an 8-byte type specifically, so if SteamId ever changed
	// size the verification would no longer apply. Belt and braces with the size check
	// further up.
	WORKSHOP_STEAM_ABI_CHECK(sizeof(SteamId) == 8,
	    "SteamId must stay 8 bytes or the verified return convention no longer applies");

} // namespace workshop

#endif // WORKSHOP_STEAMABI_H
